# Generated by Django 2.1.2 on 2018-10-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(max_length=50000),
        ),
    ]
